/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil-community/router";
export namespace Components {
    interface AboutUsPage {
    }
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface ContactUsPage {
    }
    interface DashboardHome {
    }
    interface HamburgerMenu {
    }
    interface LoginPage {
    }
    interface PackagesPage {
    }
    interface ProfileMenu {
    }
    interface UploadPage {
    }
    interface WhySociaflowPage {
    }
}
declare global {
    interface HTMLAboutUsPageElement extends Components.AboutUsPage, HTMLStencilElement {
    }
    var HTMLAboutUsPageElement: {
        prototype: HTMLAboutUsPageElement;
        new (): HTMLAboutUsPageElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLContactUsPageElement extends Components.ContactUsPage, HTMLStencilElement {
    }
    var HTMLContactUsPageElement: {
        prototype: HTMLContactUsPageElement;
        new (): HTMLContactUsPageElement;
    };
    interface HTMLDashboardHomeElement extends Components.DashboardHome, HTMLStencilElement {
    }
    var HTMLDashboardHomeElement: {
        prototype: HTMLDashboardHomeElement;
        new (): HTMLDashboardHomeElement;
    };
    interface HTMLHamburgerMenuElement extends Components.HamburgerMenu, HTMLStencilElement {
    }
    var HTMLHamburgerMenuElement: {
        prototype: HTMLHamburgerMenuElement;
        new (): HTMLHamburgerMenuElement;
    };
    interface HTMLLoginPageElement extends Components.LoginPage, HTMLStencilElement {
    }
    var HTMLLoginPageElement: {
        prototype: HTMLLoginPageElement;
        new (): HTMLLoginPageElement;
    };
    interface HTMLPackagesPageElement extends Components.PackagesPage, HTMLStencilElement {
    }
    var HTMLPackagesPageElement: {
        prototype: HTMLPackagesPageElement;
        new (): HTMLPackagesPageElement;
    };
    interface HTMLProfileMenuElement extends Components.ProfileMenu, HTMLStencilElement {
    }
    var HTMLProfileMenuElement: {
        prototype: HTMLProfileMenuElement;
        new (): HTMLProfileMenuElement;
    };
    interface HTMLUploadPageElement extends Components.UploadPage, HTMLStencilElement {
    }
    var HTMLUploadPageElement: {
        prototype: HTMLUploadPageElement;
        new (): HTMLUploadPageElement;
    };
    interface HTMLWhySociaflowPageElement extends Components.WhySociaflowPage, HTMLStencilElement {
    }
    var HTMLWhySociaflowPageElement: {
        prototype: HTMLWhySociaflowPageElement;
        new (): HTMLWhySociaflowPageElement;
    };
    interface HTMLElementTagNameMap {
        "about-us-page": HTMLAboutUsPageElement;
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "contact-us-page": HTMLContactUsPageElement;
        "dashboard-home": HTMLDashboardHomeElement;
        "hamburger-menu": HTMLHamburgerMenuElement;
        "login-page": HTMLLoginPageElement;
        "packages-page": HTMLPackagesPageElement;
        "profile-menu": HTMLProfileMenuElement;
        "upload-page": HTMLUploadPageElement;
        "why-sociaflow-page": HTMLWhySociaflowPageElement;
    }
}
declare namespace LocalJSX {
    interface AboutUsPage {
    }
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface ContactUsPage {
    }
    interface DashboardHome {
    }
    interface HamburgerMenu {
    }
    interface LoginPage {
    }
    interface PackagesPage {
    }
    interface ProfileMenu {
        "onLoginClicked"?: (event: CustomEvent<any>) => void;
    }
    interface UploadPage {
    }
    interface WhySociaflowPage {
    }
    interface IntrinsicElements {
        "about-us-page": AboutUsPage;
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "contact-us-page": ContactUsPage;
        "dashboard-home": DashboardHome;
        "hamburger-menu": HamburgerMenu;
        "login-page": LoginPage;
        "packages-page": PackagesPage;
        "profile-menu": ProfileMenu;
        "upload-page": UploadPage;
        "why-sociaflow-page": WhySociaflowPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "about-us-page": LocalJSX.AboutUsPage & JSXBase.HTMLAttributes<HTMLAboutUsPageElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "contact-us-page": LocalJSX.ContactUsPage & JSXBase.HTMLAttributes<HTMLContactUsPageElement>;
            "dashboard-home": LocalJSX.DashboardHome & JSXBase.HTMLAttributes<HTMLDashboardHomeElement>;
            "hamburger-menu": LocalJSX.HamburgerMenu & JSXBase.HTMLAttributes<HTMLHamburgerMenuElement>;
            "login-page": LocalJSX.LoginPage & JSXBase.HTMLAttributes<HTMLLoginPageElement>;
            "packages-page": LocalJSX.PackagesPage & JSXBase.HTMLAttributes<HTMLPackagesPageElement>;
            "profile-menu": LocalJSX.ProfileMenu & JSXBase.HTMLAttributes<HTMLProfileMenuElement>;
            "upload-page": LocalJSX.UploadPage & JSXBase.HTMLAttributes<HTMLUploadPageElement>;
            "why-sociaflow-page": LocalJSX.WhySociaflowPage & JSXBase.HTMLAttributes<HTMLWhySociaflowPageElement>;
        }
    }
}
