/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil-community/router";
export namespace Components {
    interface AboutUsPage {
    }
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface LoginBtn {
    }
    interface LoginPage {
    }
    interface MenuBar {
    }
}
declare global {
    interface HTMLAboutUsPageElement extends Components.AboutUsPage, HTMLStencilElement {
    }
    var HTMLAboutUsPageElement: {
        prototype: HTMLAboutUsPageElement;
        new (): HTMLAboutUsPageElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLLoginBtnElement extends Components.LoginBtn, HTMLStencilElement {
    }
    var HTMLLoginBtnElement: {
        prototype: HTMLLoginBtnElement;
        new (): HTMLLoginBtnElement;
    };
    interface HTMLLoginPageElement extends Components.LoginPage, HTMLStencilElement {
    }
    var HTMLLoginPageElement: {
        prototype: HTMLLoginPageElement;
        new (): HTMLLoginPageElement;
    };
    interface HTMLMenuBarElement extends Components.MenuBar, HTMLStencilElement {
    }
    var HTMLMenuBarElement: {
        prototype: HTMLMenuBarElement;
        new (): HTMLMenuBarElement;
    };
    interface HTMLElementTagNameMap {
        "about-us-page": HTMLAboutUsPageElement;
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "login-btn": HTMLLoginBtnElement;
        "login-page": HTMLLoginPageElement;
        "menu-bar": HTMLMenuBarElement;
    }
}
declare namespace LocalJSX {
    interface AboutUsPage {
    }
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface LoginBtn {
        "onLoginClicked"?: (event: CustomEvent<any>) => void;
    }
    interface LoginPage {
    }
    interface MenuBar {
    }
    interface IntrinsicElements {
        "about-us-page": AboutUsPage;
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "login-btn": LoginBtn;
        "login-page": LoginPage;
        "menu-bar": MenuBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "about-us-page": LocalJSX.AboutUsPage & JSXBase.HTMLAttributes<HTMLAboutUsPageElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "login-btn": LocalJSX.LoginBtn & JSXBase.HTMLAttributes<HTMLLoginBtnElement>;
            "login-page": LocalJSX.LoginPage & JSXBase.HTMLAttributes<HTMLLoginPageElement>;
            "menu-bar": LocalJSX.MenuBar & JSXBase.HTMLAttributes<HTMLMenuBarElement>;
        }
    }
}
